# Generated by Django 3.2.4 on 2021-09-21 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20210920_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='dinner3_recipe',
            field=models.ManyToManyField(blank=True, related_name='dinner3recipe', to='planner.Recipe'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='saved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
