# Generated by Django 3.2.4 on 2021-09-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20210921_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='dinner3_recipe',
        ),
    ]
