# Generated by Django 3.2.4 on 2021-09-21 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_remove_mealplan_dinner3_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='breakfast1_recipe',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='breakfast1_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast1recipe', to='planner.recipe'),
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='breakfast2_recipe',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='breakfast2_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast2recipe', to='planner.recipe'),
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='breakfast3_recipe',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='breakfast3_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast3recipe', to='planner.recipe'),
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='dinner1_recipe',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='dinner1_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinner1recipe', to='planner.recipe'),
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='dinner2_recipe',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='dinner2_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinner2recipe', to='planner.recipe'),
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='lunch1_recipe',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='lunch1_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch1recipe', to='planner.recipe'),
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='lunch2_recipe',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='lunch2_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch2recipe', to='planner.recipe'),
        ),
    ]
